### ISSUE TITLE
Can the scroll be on the whole page?

### ISSUE THREAD

**Issue by baruchiro** [yonatanmgr/opensource-il-site#15]
On a small screen, I feel like I don't see the whole content, so I'm trying to scroll, but it didn't work.

![image](https://user-images.githubusercontent.com/17686879/229043077-fcfda58d-abb5-406f-a12a-526eb91cfc54.png)

Then I found that I have to put the mouse on the list to scroll the list, and on the README to scroll the readme.

**Comment by yonatanmgr** [comment]
Closing for now :)
