### ISSUE TITLE
"Last version time" sorting issue

### ISSUE THREAD

**Issue by sagi403** [yonatanmgr/opensource-il-site#16]
I encountered an issue with sorting by the "Last version time" in ascending and descending order, where the minimum open issue remains stuck and cannot be moved from its position if I keep switching between ascending and descending order.
![issue](https://user-images.githubusercontent.com/95089762/229168180-146351b2-424b-4a22-a745-50dd8fe26830.JPG)

**Comment by yonatanmgr** [comment]
Closed by #17
