### ISSUE TITLE
UX suggestion for the sort button

### ISSUE THREAD

**Issue by ErezBiren** [yonatanmgr/opensource-il-site#18]
Wouldn't it be better to show an up arrow or a down arrow instead of both?
I think that It's more clear in the eyes and more common approach.
![image](https://user-images.githubusercontent.com/7828909/229266181-69d505cd-ce4a-4b11-8d43-2560eddfd075.png)

Change to:
![image](https://user-images.githubusercontent.com/7828909/229268237-2d4ffcf2-2700-43e9-88aa-c8eea16c1d09.png)

I'll be glade to take this one.

**Comment by yonatanmgr** [comment]
Great idea! And with the default sort by last commit, that'll work nice as the user would immediately know how the projects are sorted.
Assigning you

**Comment by ErezBiren** [comment]
As I think about it now.
In that way, there will be also a default sort on all of them.
Not sure if we want that

**Comment by yonatanmgr** [comment]
Already fixed by #60
