### ISSUE TITLE
Make an exit instead of the x button by clicking outside the box

### ISSUE THREAD

**Issue by CodeBreaker6** [yonatanmgr/opensource-il-site#24]
![image](https://user-images.githubusercontent.com/90083761/232246192-d4116a18-4782-4622-b86b-b695a9522b9a.png)

**Comment by UrielOfir** [comment]
@CodeBreaker6 
I think you can assign yourself and start working on fixing this issue.

**Comment by yaelih** [comment]
What about having both functionalities? I wouldn't remove the X. 
I would add that functionality, not do it instead of the x button.

**Comment by CodeBreaker6** [comment]
> What about having both functionalities? I wouldn't remove the X. I would add that functionality, not do it instead of the x button.

This is in addition to the 'X' button.
