### ISSUE TITLE
בלחיצה על חברה אי אפשר לבטל את הסינון בלי לרענן -> הוספת כפתור של פילטר לפי חברה

### ISSUE THREAD

**Issue by RoyTennenbaum** [yonatanmgr/opensource-il-site#43]
אם לוחצים על חברה בדף החברות מתקבלת רשימה של כל הRepos שקשורים לאותה החברה, אך אין אפשרות לחזור חזרה ולבטל את הסינון אלא אם כן מרעננים את האתר.

הצעה לייעול שלי:
הוספת כפתור נוסף לרשימת הפילטרים בצורת dropdown, כשהאופציה הראשונה תיקרא "כל החברות" ובdropdown שמות של כל חברה :)

**Comment by eylonxx** [comment]
we can add this logic to the reset button suggested in #41

**Comment by eylonxx** [comment]
Upon further investigation, it seems like the variable that stores all of the data (all the repos), is being overwritten with the data from the fetch made by fetching a company's repos so I think a bigger change may be needed.
Will look into this more tonight.

**Comment by yonatanmgr** [comment]
Please look into it! I'm thinking about changing how the API works and it seems like a good opportunity to rethink how the rendering and data caching works on the client side.

**Comment by yonatanmgr** [comment]
> אם לוחצים על חברה בדף החברות מתקבלת רשימה של כל הRepos שקשורים לאותה החברה, אך אין אפשרות לחזור חזרה ולבטל את הסינון אלא אם כן מרעננים את האתר.
> 
> הצעה לייעול שלי: הוספת כפתור נוסף לרשימת הפילטרים בצורת dropdown, כשהאופציה הראשונה תיקרא "כל החברות" ובdropdown שמות של כל חברה :)

And I'll be glad if you could translate your issue and title to English, as it seems we're working internationally now! 😉 @RoyTennenbaum

**Comment by yonatanmgr** [comment]
Closing after the refactoring and thanks to #56
