### ISSUE TITLE
Markdown in ReadmePreview not parsed correctly

### ISSUE THREAD

**Issue by shacharRonZohar** [yonatanmgr/opensource-il-site#48]
Since the markdown is taken as a string and parsed as regular html, it misses some important parts from GitHub readme markdown presentation.

Consider this title part of a readme preview, that currently looks like this:

![wrong-markdown](https://github.com/lirantal/awesome-opensource-israel/assets/88171079/87e93a91-edf6-4543-885f-4770e9e76004)

While the actual readme looks like this:
![correct-markdown](https://github.com/lirantal/awesome-opensource-israel/assets/88171079/3ad022f3-bf7d-47e4-8563-2fc4495d6287)

I prototyped a solution using [marked](https://www.npmjs.com/package/marked), which allows us to parse and render the correct HTML quickly and without implementing our own parser, and would love to submit a PR if there is interest in using this particular library, or any other.

**Comment by eylonxx** [comment]
Will this also fix #9 ?

**Comment by yonatanmgr** [comment]
Sounds good! Could you submit a PR which uses marked instead of showdown and we'll see if it works better? @shacharRonZohar

**Comment by shacharRonZohar** [comment]
> Will this also fix #23 ?

@eylonxx possibly, although I suspect we will need to add a further emoji parsing layer, since I doubt that marked or any library will keep a collection of all possible emojis themselves.

@yonatanmgr for sure! I'll work on it today and see if it helps at all

**Comment by shacharRonZohar** [comment]
Looks like it worked well, filed a simple PR with the changes.

It looks like that Emoji parsing (for #23) will need further enhancements, but we can probably use marked for that with some plugin.

**Comment by yonatanmgr** [comment]
Resloved in #49
