### ISSUE TITLE
Youtube link breaks responsive header layout

### ISSUE THREAD

**Issue by yonatanmgr** [yonatanmgr/opensource-il-site#51]
It seems like #50 broke the header layout in mobile and tablet.

![image](https://github.com/yonatanmgr/opensource-il-site/assets/31913495/f8bbcaff-db28-4879-b202-864287a69eec)

In addition, while the Youtube icon is in the right height, it is too wide and doesn't fit with the rest of the icons.

![image](https://github.com/yonatanmgr/opensource-il-site/assets/31913495/e68d43ba-1bd5-41ee-9865-65f253c7b4df)

Assigning @DrVickie8 for now :)

**Comment by DrVickie8** [comment]
Thank you @yonatanmgr, I will work on this.

**Comment by yonatanmgr** [comment]
Closing as we now have a dedicated social link
