### ISSUE TITLE
Buttons font color is black and not readable

### ISSUE THREAD

**Issue by GilShechter** [yonatanmgr/opensource-il-site#6]
### Issue 

The buttons font color appears black on dark background in Chrome (PC),
which makes the text not readable.

### Preview

![image](https://user-images.githubusercontent.com/85102059/227723892-6b743614-cd95-4b4f-a52d-02e623504ebe.png)

**Comment by yonatanmgr** [comment]
Fixed with the last commit & thanks to @oriklar 's pull request :)
